<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId());
} else {
    $customerData = new Varien_Object();
}
?>
<?php $customFields = $this->getCustomFields(); ?>
<?php $customFieldsValues = unserialize($customerData->getCustomFieldsValues()); ?>
<div class="container-fluid main-container vendor-container">
    <h1><?php echo Mage::helper('marketplace')->__('Manage Profile Info'); ?></h1>
    <div class="row">
        <div class="span12 container-fluid form-container">
            <form name="settings_supplier_profile" id="settings_supplier_profile" action="<?php echo Mage::getUrl('marketplace/settings/profileSave') ?>" method="post" enctype="multipart/form-data">
                <div class="span6">
                    <div class="container form-group">
                        <div class="cont">
                        <div class="span3 label-container">
                            <label for="name" class="required">
                                <?php echo $this->__('Name'); ?> <em>*</em>
                            </label>
                        </div>
                        <div class="span5 input-container">
                            <input type="text" id="name" name="name" class="input-text required-entry form-control validate-length maximum-length-60" value="<?php echo $customerData->getSupplierName(); ?>" />
                        </div>
                    </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="container form-group">
                        <div class="cont">
                            <div class="span3 label-container">
                                <label for="description" class="required">
                                    <?php echo $this->__('Description'); ?> <em>*</em>
                                </label>
                            </div>
                            <div class="span8 input-container">
                                <textarea name="description" id="description" rows="14" class="input-text form-control wysiwyg"><?php echo $customerData->getSupplierDescription(); ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if($customFields): ?>
                    <?php foreach($customFields AS $field): ?>
                        <div class="span6">
                            <div class="container form-group">
                                <div class="cont">
                                    <div class="span3 label-container">
                                        <label for="<?php echo $this->escapeHtml($field->getName()); ?>" <?php echo $field->getIsRequired() ? 'class="required"' : ''; ?>>
                                            <?php echo $this->escapeHtml($field->getLabel()); ?>
                                            <em><?php echo $field->getIsRequired() ? '*' : ''; ?></em>
                                        </label>
                                    </div>
                                    <div class="span8 input-container">
                                        <?php echo $this->getCustomField($field, $customFieldsValues); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="span6">
                    <div class="container form-group">
                        <div class="radio">
                            <label>
                                <input type="checkbox" name="profile_enabled"<?php echo $customerData->getSupplierProfileVisible() ? ' checked="checked"' : ''; ?>> <?php echo $this->__('Profile Page Enabled'); ?>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="span12">
                    <input type="submit" name="submit" class="btn btn-primary" value="<?php echo $this->__('Save') ?>" />
                </div>
                <?php if($customerData->getSupplierNameNew() || $customerData->getNewCustomFieldsValues()) : ?>
                    <div class="span12">
                        <div class="container">
                            <div class="row">
                                <div class="container"><h3><?php echo $this->__('Waiting for review by admin'); ?></h3></div>
                            </div>
                            <?php if($customerData->getSupplierNameNew()): ?>
                                <div class="row">
                                    <h5><?php echo $this->__("Title"); ?> :</h5>
                                    <p><?php echo $this->escapeHtml($customerData->getSupplierNameNew()); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($customerData->getSupplierDescriptionNew()): ?>
                                <div class="row">
                                    <h5><?php echo $this->__("Description"); ?> :</h5>
                                    <p><?php echo $this->escapeHtml($customerData->getSupplierDescriptionNew()); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if(!is_array($customFieldsValues)) $customFieldsValues = array(); ?>
                            <?php foreach($customFieldsValues AS $customValue) : ?>
                                <div class="row">
                                    <h5><?php echo $this->escapeHtml($customValue['name']); ?> :</h5>
                                    <p><?php echo $this->escapeHtml($customValue['value']); ?></p>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="span12">
                        <input type="submit" name="clear" class="btn btn-warning" value="<?php echo $this->__('Clear text') ?>" />
                    </div>
                <?php endif; ?>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('settings_supplier_profile');
    //]]>

    jQuery(document).ready(function(){
        jQuery('.datepicker').datepicker();
        jQuery('.wysiwyg').wysihtml5({
            color: true,
            html: true,
            image: false
        });
    });
</script>
