<?php $_order = $this->getOrder(); ?>
<div class="container vendor-container">
    <div class="hero-unit">
        <h2 style="text-align: center"><?php echo $this->__('Order'); ?> #<?php echo $_order->getIncrementId(); ?></h2>

        <div class="container">
            <div class="row">
                <div class="span5">
                    <h3><?php echo $this->__("Order Information"); ?></h3>
                    <p><strong><?php echo $this->__("Order Date"); ?> : </strong> <?php echo date("M d, Y g:i:s A", strtotime($_order->getCreatedAt())); ?></p>
                    <p><strong><?php echo $this->__("Order Status"); ?> : </strong>
                        <?php if($_order->getStatus() == 'canceled') :?>
                            <span class="text-danger"><?php echo ucfirst($_order->getStatus()); ?></span>
                        <?php else : ?>
                            <?php echo ucfirst($_order->getStatus()); ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="span5">
                    <h3><?php echo $this->__("Account Information"); ?></h3>
                    <p><strong><?php echo $this->__("Customer Name"); ?> : </strong> <?php echo $this->escapeHtml($_order->getCustomerFirstname()); ?> <?php echo $this->escapeHtml($_order->getCustomerLastname()); ?></p>
                    <p><strong><?php echo $this->__("Email"); ?> : </strong> <a href="mailto:<?php echo $_order->getCustomerEmail(); ?>"><?php echo $this->escapeHtml($_order->getCustomerEmail()); ?></a></p>
                </div>
            </div>
        </div>
    </div>

    <div class="tab-content">
        <ul class="nav nav-tabs nav-justified" role="tablist">
            <li class="active"><a href="#order" role="tab" data-toggle="tab">Order</a></li>
            <li><a href="#shipments" role="tab" data-toggle="tab">Shipments</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="order">
                <?php echo $this->getChild('view_order')->setOrder($_order)->setItems($this->getItems())->toHtml(); ?>
            </div>
            <div class="tab-pane" id="shipments"><?php echo $this->getChild('view_shipments')->setOrder($_order)->toHtml(); ?></div>
            <div class="tab-pane" id="history"><?php echo $this->getChild('view_history')->setOrder($_order)->toHtml(); ?></div>
        </div>
    </div>
</div>