<?php /*
<div class="container">
    <div class="content">
        <div class="row">
            <div class="login-form">
                <h2><?php echo $this->__('Log in'); ?></h2>
                <?php if(Mage::helper('supplierfrontendproductuploader')->noAccessInformation()): ?>
                    <div class="alert alert-error">
                        <strong><?php echo $this->__('Sorry') ?>!</strong> <?php echo $this->__('It looks like you are logged in, but you do not have access to this page. Please contact website administrator.') ?>
                    </div>
                <?php endif; ?>
                <form name="login_form" id="login_form" action="<?php echo Mage::getBaseUrl() ?>supplierfrontendproductuploader/login/login/" method="POST">
                    <fieldset>
                        <div class="clearfix">
                            <input type="email" name="email" placeholder="example@example.com" class="input-text required-entry validate-email">
                        </div>
                        <div class="clearfix">
                            <input type="password" name="password" placeholder="Password" class="input-text required-entry">
                        </div>
                        <button class="btn primary" type="submit"><?php echo $this->__('Sign in'); ?></button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('login_form');
    //]]>
</script>
*/
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create a Supplier Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra')?>
    <form name="login_form" id="login_form" action="<?php echo Mage::getBaseUrl() ?>supplierfrontendproductuploader/login/login/" method="POST">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Supplier') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to sell your product online.') ?></p>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content">
                    <h2><?php echo $this->__('Registered Suppliers') ?></h2>
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::getBaseUrl()."supplierfrontendproductuploader/register"?>'"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var customForm = new VarienForm('login_form');
    //]]>
    </script>
</div>